### ISSUE TITLE
Go and cockroachdb versions no longer officially supported

### ISSUE THREAD

**Issue by craig-osterhout** [olliefr/docker-gs-ping-roach#3]
Hi @olliefr,

Since Go 1.16 and cockroachdb 20.1 is no longer officially supported, can this sample be updated to a newer versions?
If necessary, I can help create a PR here and in the Docker Docs if no concerns.

Related to https://github.com/olliefr/docker-gs-ping/issues/8

**Comment by olliefr** [comment]
Hi @craig-osterhout!

Thank you for noticing this. It's been a while since I worked on this application. Please feel free to submit a PR and I will approve as a matter of priority :shipit:

**Comment by olliefr** [comment]
Hey, @craig-osterhout, I've scheduled some time to complete this task once https://github.com/docker/docs/pull/16867 is merged.

**Comment by olliefr** [comment]
This repository had now been migrated to Docker GitHub org: https://github.com/docker/docker-gs-ping-roach

I'm going to archive the current repo.

:shipit:
